import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // 👈 use Montserrat
import "./globals.css";
import { ChatBot } from "@/components/ChatBot";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // you can choose which weights to use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        {children}
        <ChatBot />
      </body>
    </html>
  );
}
